name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')

  update-homebrew:
    needs: [release]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - id: version
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - id: checksum
        run: |
          SHA256=$(curl -sfL https://github.com/kaiiy/aicommits/archive/refs/tags/${{ steps.version.outputs.version }}.tar.gz | sha256sum | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - uses: peter-evans/repository-dispatch@v3
        with:
          repository: kaiiy/homebrew-tap
          event-type: update-brew
          client-payload: '{ "formula": "aicommits", "url": "https://github.com/kaiiy/aicommits/archive/refs/tags/${{ steps.version.outputs.version }}.tar.gz", "sha256": "${{ steps.checksum.outputs.sha256 }}" }'
